yeoman/yeoman.io

app/learning/deployment.md
app/learning/faq.md
app/learning/index.md
app/learning/support.md

As part of https://github.com/yeoman/yeoman.io/issues/416, the `learning` section to decouple from Grunt.
I do not think this directly fixes - https://github.com/yeoman/yeoman.io/issues/416, other pages on the site mush be changed too.
Happy 2015! :beers:

Decouple grunt

---

app/authoring/file-system.md

This commit is in regards to [this yeoman generator issue](https://github.com/yeoman/generator/issues/764#issuecomment-74595150)
I am not confident in the wording mostly because I would like it to say:
"fs.commit should only be used in this circumstance"
However, I don't understand in what circumstance it should be used.  That is why I just said its use was unsupported, which is ambiguous.
Also, I wasn't able to figure out how to build yeoman.io locally.  On the 'bundler install' step I received [this output](https://gist.github.com/olsonpm/50c25bf2ebfa32777fe9).  I won't worry about it due to this commit being documentation only.

updating documentation for fs.commit gotcha

---

app/authoring/index.md

While reading this page for the first time:
http://yeoman.io/authoring/
It took me a moment to figure out where to put the supplied generator code. This change explicitly references the file (`app/index.js`) that can contain the code.
I hope this will save someone else a few minutes of confusion when they write their first generator.

Explicitly call out generator code location

---

app/codelab/write-app.md

If the Todos list is included within the form, addTodo() is also called when the X button (added in the next step) is clicked. Closing the form after the first input row, and keeping the list of entered todos out of the form so that ng-submit is only bound to one button, ensures that addTodo is only called when "Add" is clicked.

restore previous placement of </form>

---

app/authoring/file-system.md

Updating 'contains' to 'contain' as it makes more sense in the current context.

Fixing typo.

---

app/contributing/index.md

We actually have no official gulp plugins, right?

contributing/index: correct `plugins and modules` section

---

app/codelab/write-unit-tests.md

I noticed that the files array gets updated automatically by Yeoman now to include bower dependencies in the karma.conf.js file for you.

Updated files array to reflect current behaviour

---

app/codelab/install-generators.md

The current version mentioned in the docs 0.9.2 throws a warning in the
"wiredep:app" task. Discussed at 
https://github.com/yeoman/yeoman.io/issues/389

Updates Angular Generator version. Fixes #389

---

app/authoring/index.md

Taking into account the prevalence of "your" throughout the article, I assume that this instance of "our" was merely a typo.
Merely a typo, I say!

Adding our own => Adding your own

---

app/codelab/install-generators.md
app/codelab/setup.md

Don't suggest `sudo` and instead directly link to Sindre's guide. Also cleanup the wording a little.
Fix https://github.com/yeoman/yeoman.io/issues/470

Fix notes about permission errors

---

app/index.html

Remove two outdated talks/screencasts from the home page. Both are not relevant to the current yeoman workflow anyways.
Fix #414

Remove two outdated talks on the homepage

---

app/authoring/user-interactions.md

The sentence describing the use of the `store` property was grammatically incorrect and unclear. Reworded the sentence to improve readability and to clarify how the property behaves.

Reword and clarify prompt store property

---

Gruntfile.js
package.json

Fixes this error:
```
Uncaught RangeError: Maximum call stack size exceeded livestyle-client.js:60
```
also opens browser when server is started

Upgrade grunt-livestyle and disable css background-image watching

---

package.json

This should take care of some of those errors in the travis build.
- Updated image optimization binaries
- Updated autoprefixer implementation

Update grunt-reduce to 2.1.1

---

app/authoring/index.md

Later in the "Authoring" guide, [there are examples which refer to APIs not present in 0.17.3](http://stackoverflow.com/questions/31124053/yeoman-generator-throws-the-error-object-has-no-method-templatepath)., so the existing `package.json` doesn't work.

use current version of yeoman-generator

---

package.json

Fixes warnings in autoprefixer transform

Update grunt-reduce to 2.1.2

---

app/authoring/running-context.md

While I want to create a generator first time,
I roll to the bottom, but can't figure out what does `default` mean.
I thought adding this piece of simple description will be much more friendly to whom is new to yeoman.

Add description to priority: default

---

app/assets/js/generator.js
app/generators/index.html

The "sorting by installs" is not working.
http://yeoman.io/generators/
I corrected the attribute to fix it.

Fix: sort by installs

---

app/assets/css/main.css
app/assets/js/generator.js
app/generators/index.html

Make installs, downloads less prominent (smaller).
Adds a sort on the last updated field. Also fixes a bug around showing the last updated field (wouldn't show if the author didn't have a name displayed)
Description spans the whole row now.
Mobile styles need some loving.

make name and description more prominent

---

app/authoring/index.md

It mentions both directory structured, but only includes a single example of the `files` property.
Added an example for the second directory structure.

update authoring docs with second example of package.json

---

app/authoring/user-interactions.md

as far as there is no such option in the actual code https://github.com/yeoman/generator/blob/master/lib/base.js#L289-L295

authoring/user-interactions: remove banner field for argument’s hash

---

app/assets/css/main.css

Resolves #566 by adjusting the styles to ensure the footer remains pushed to the bottom of the page.

Stretches the content container to always fill the screen

---

package.json

Fixed build error where duplicateFavIcon transform would die on google site verification html file.
Adds source maps.
ping @eddiemonge

Update to grunt-reduce 2.2.0

---

app/assets/js/generator.js

Putting back the initialization of the '#plugin-all' element (in the generator list view) using its template.
A fix for the issue https://github.com/yeoman/yeoman.github.io/issues/580.

Fixing the generator list displaying error

---

app/generators/index.html

Two 'ago's appear in the table.

Removed extra 'ago' from 'Last Updated' section in the generators table

---

readme.md

Jekyll Serve command was missing in the Readme and the next steps weren't clear. I had to do a lot of digging in the issues panel to find this.

Added Jekyll Serve command to Readme.md

---

app/assets/css/main.css
app/generators/index.html

There were a couple of elements in the generator-listing page, which I felt could be improved. So, I tweaked the table a little bit and modified the styles. Let me know what you think. cc @hemanth

Changed table structure in Generators List Page

---

app/learning/index.md

Related to updates we talked in #568
Changing the branding to being more a "generic scaffolding" tool. Also, this new getting started guide really covers every yo features, as before it wasn't giving a lot of details about how you'd use yo.

Make the getting started section only about Yeoman

---

app/contributing/testing-guidelines.md

One of the claims here is false:
> "You're guaranteed that `this` is a totally new object each time a test is run."
This feature exists in jasmine, but not mocha. In mocha, the "this" context **does not** get cleared out for each test run, but in fact sticks around for an entire suite. This can cause pollution itself, since variables can now travel outside of their scope. E.g.:
```
describe('mySuite', function() {
describe('myComponent', function() {
beforeEach(function() {
this.controller = foo
});
it('does something', function() {
this.controller.doSomething();
});
});
it('does something else', function() {
this.controller // => foo 
});
});
```
I deleted the section because I don't think there's a simple way to explain this quirk. Maybe it makes sense to just add "if you're using …

Remove scoped variables section

---

app/authoring/composability.md

I got quite confused by just the docs as they are, trying to implement my own generator that composes another generator. After finding this example generator-generator <- generator-node, I discovered some nice tricks in it, like how to actually pass the `skipInstall` option (that the dashed-name is magically converted to camelCase), that the `composeWith` method should be placed inside the `default` group etc. I think a link to such a maintained complex example would be useful to people reading the docs.

Link to practical composability example

---

app/authoring/debugging.md

Hopefully more Windows developers are using PowerShell than Command Prompt, and this will help them out since "where" is actually a command for filtering data passed into it.

Add PowerShell version of the Windows instructions

---

app/authoring/dependencies.md

Closes yeoman/generator#933
I tested both actually.
```
installingLodash: function() {
this.npmInstall(['lodash'], { 'saveDev': true });
}
```
VS.
```
installingLodash: function() {
this.npmInstall(['lodash'], { 'save-dev': true });
}
```
They worked both with npm `v3.10.8`.

Fix npm options example

---

app/learning/deployment.md

I had trouble finding the `build` task, until I realised it was a `gulp` task. Made it clearer.
New to Yeoman, so if `gulp build` is only used sometimes, feel free to close & ignore.

Changed build to gulp build

---

app/authoring/index.md

in the next documentation page we're instructed of not using console.log, why showing it up in the first tutorial page then?
It'd probably be better to have the tutorials reflect best practices as much as possible to avoid bad copy/pasting of code.

replacing console.log by this.log

---

app/authoring/index.md

In the context of this sentence, I don’t think it makes much sense to link directly to the documentation of the `files` property.

Fix link to `package.json` documentation

---

app/authoring/file-system.md

Get rid of erroneous parenthesis at the end of source extends for sourceRoot example

---

app/authoring/file-system.md

If you look at [`gulp-beautify` README](https://www.npmjs.com/package/gulp-beautify) it expects `indent_size` rather than `indentSize`.

Fixed property name beautify listing

---

app/codelab/setup.md

Update the install prerequisites section, as while Yeoman only requires Node.js >= v4, the Fountain Webapp Generator [requires v6.0.0 or higher](https://github.com/FountainJS/generator-fountain-webapp#requirement-node-6--npm-3).

Update Install prerequisites

---

app/authoring/user-interactions.md

Minor capitalisation fix

---

app/authoring/running-context.md

This is the wrong tense and doesn't work, grammatically: 'Each task is running in sequence by the Yeoman environment run loop.'

Corrected 'is running' to 'is run' on line 13

---

app/authoring/debugging.md

`node --inspect` is a great alternative to `node --debug`, suggest using
it.
TBH since `node --inspect` became a thing (Node 6.x) I haven't used
`node --debug`, and I suspect that's true for a lot of people. I think
ideally we'd suggest `node --inspect`, and offer `node --debug` as a
backup.
If I messed up something about the PR let me know!

Suggest node --inspect for debugging

---

app/_includes/foot.html

That’s it. 
Closing #744 and related to #529.

Fix mixed content error when serving via https

---

app/authoring/testing.md

As there is no way to access the `generator` (not that i know of) created in `beforeEach` in `it` to write the test cases, example should show `run` method in `it`.

moving `helpers.run` from `beforeEach` to `it`

---

app/authoring/dependencies.md

I explain how to manage dependencies as what we used to do at `package.json`. This method is used at `generator-node/generators/eslint/index.js`. I consider it can be useful if it explains in documentation.

Add managing dependencies as package.json

---

.travis.yml
Gruntfile.js

bundle exec jekyll doctor --source app didn’t worked because the app directory is missing a jekyll config file.

Fix deployment via travis

---

_config.yml

Fix https://travis-ci.org/yeoman/yeoman.github.io/builds/369319754#L1045
- `gems` is now `plugins`
-  list `jekyll-paginate` in `plugins`
- `kramdown` and `rouge` are already the default

Fix Jekyll deprecation warnings

---

app/_includes/foot.html

Stickermule removed the marketplace so this link is now 404ing. Unless there is another place you are selling. I just removed it.

Stickermule removed the market place :(

---

Gruntfile.js
_config.yml
app/_redirects

This fixes the 404 error which appears at the url http://yeoman.io/generator after moving the hosting to netlify.
Right now it redirects to http://yeoman.github.io/generator 
It would be possible to use a [rewrite](https://www.netlify.com/docs/redirects/#rewrites-and-proxying) instead if we could set up a base href in the generated docs. 
This needs further investigation. Going to merge this to eliminate the dead link.

Add rewrite rule for API docs

---

app/authoring/composability.md

Documented the [new overload of the `composeWith method`](https://github.com/yeoman/generator/pull/1099).

#composeWith object as first parameter overload

---

app/_includes/head.html
app/_layouts/base.html
app/_layouts/default.html
app/index.html

👋 team,
TL;DR: Add a learn-as-you-type search experience to the documentation
I'm working at Algolia on the a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like [react](https://reactjs.org/), [Bootstrap](https://getbootstrap.com/), [Brew](https://brew.sh/) or [jQuery](https://jquery.com/).
I have created [a preview of this PR](https://docsearch-yeoman.netlify.com/) and what DocSearch on the yeoman website could will look like here. Feel free to try it and let us know what you think. Please note the learn-as-you-type experience and the typo tolerance:
[![demo of DocSearch + …

[doc website] Add a nice search experience

---

readme.md

Clarify yeoman/yeoman is workflow focused and provide helpful links to yeoman core system repos.
I did get confused after reading the original sentence, and it is probably my fault. I followed the link from this `readme.md` that indicated Yeoman's source code was at https://github.com/yeoman/yeoman.
> If you want to submit an issue about Yeoman's source code or workflow please visit the [yeoman/yeoman repository](https://github.com/yeoman/yeoman).
It took me a few minutes to get myself set straight -- I did ask myself "_Did... did they delete yeoman's source code?_" when I was poking around the yeoman/yeoman repo.
I figured this may be an opportunity to improve the readme docs, in this very very small way.

[Documentation] Clear up potential confusion from readme.md

---

app/authoring/debugging.md

`--node-arg` was removed in npx version 7.
See https://stackoverflow.com/questions/66459448/how-do-i-use-node-arg-in-npx-npm-version-7

Update debugging.md to match new npx options

---

app/learning/faq.md

Hi!
I've started to explore the yeoman ecosystem and out of curiosity clicked on the cmder URL in the FAQ, only to find myself on a shady-looking website. Therefore I'm making a minimal pull request to update this URL so that people don't get ferried into stormy waters. Easy enough of a fix.
The rest of the links are okay - checked to make sure.
Cheers,
JP

fix: wrong cmder URL in faq.md

---

app/authoring/composability.md
app/authoring/dependencies.md
app/authoring/file-system.md
app/authoring/index.md
app/authoring/integrating-yeoman.md
app/authoring/running-context.md
app/authoring/testing.md
app/authoring/user-interactions.md

With the release of `yeoman-generator` `v6`, generators need to be ESM Modules.

fix: Update Creating Generator instructions

---

app/index.html
app/learning/index.md

Fixes #416.
Suggests npm scripts in the two main places that mention Grunt and Gulp as potential build systems:
* `/` under _Tools_
* `/learning` under _Basic Scaffolding_
Is there anywhere else we'd want the phrasing to be updated? After #417 I think much of the decoupling was already done. I found the rest of the site to be pretty good at keeping things agnostic, but didn't dive too deep.

feat: suggest npm scripts over Grunt or Gulp in first learning flow
