yeoman/yeoman.io

app/authoring/user-interactions.md

Just fixed up some typos I noticed when reading the Yeoman documentation the other day, and I thought I'd take the initiative to fix them :).

Minor update to user-interactions.md

---

app/learning/index.md

Minsafe flag has been removed from generator-angular.

Changed --minsafe flag to --coffee.

---

app/_posts/blog/2014-03-04-performance-optimization.md

gulp-ngmin is deprecated: https://github.com/sindresorhus/gulp-ngmin

Replace gulp-ngmin with gulp-ng-annotate

---

app/assets/js/script.js
app/blacklist.json

related to https://github.com/yeoman/yo/issues/261

move blacklist to separate file

---

app/authoring/running-context.md

Very small spelling fix on the documentation

Minor spelling fix

---

app/_posts/blog/2014-03-04-performance-optimization.md

I thought creating an issue would be unnecessary since I could just do the work my self.
Changed from 'wel' to 'well' on line 137.

Fixed typo in blog post

---

app/authoring/file-system.md

Updating file-system.md

---

app/_includes/sidebars/authoring.html
app/authoring/integrating-yeoman.md

Started to work on the documentation to integrate Yeoman in third-party tools.
Comments / typo fixes are welcomed :)

Add yeoman-environment documentation

---

app/codelab/setup.md

Fix https://github.com/yeoman/yeoman.io/issues/354

recommend readers to install the latest npm

---

app/_includes/foot.html
app/_layouts/default.html
app/_layouts/single-column.html
app/_posts/blog/2013-08-23-hello-1.0.md
app/_posts/blog/2014-02-03-gulp-explore.md
app/_posts/blog/2014-03-04-performance-optimization.md
app/_posts/blog/2014-05-12-generator-karma-rewrite.md
app/_posts/blog/2014-10-14-release-0.18.md
app/authoring/composability.md
app/authoring/dependencies.md
app/authoring/getting-started.md
app/authoring/index.md
app/authoring/testing.md
app/codelab.md
app/codelab/install-generators.md
app/codelab/keep-going.md
app/codelab/local-storage.md
app/codelab/meet-yeoman.md
app/codelab/setup.md
app/codelab/write-app.md
app/index.html
app/learning/deployment.md
app/learning/faq.md
app/learning/index.md
app/learning/resources.md
app/learning/support.md

This updates all links that resulted in 301 and 302 redirect chains so they point at the correct resource.
I used [hyperlink](https://github.com/Munter/hyperlink) to find the problems

Link fixes

---

app/authoring/testing.md

[BUGFIX] change withPrompt to withPrompts

---

app/codelab/write-unit-tests.md

Fix code style of #462

---

app/blacklist.json

Exclude duplicate generator of "angular-fullstack"

---

app/index.html

Add @arthurvr to the team

---

app/authoring/user-interactions.md

Use gender-neutral language

---

app/assets/css/main.css
app/assets/js/generator.js
app/generators/index.html

Merge the author, website, name and description fields to display more
description info. Also sorting on description was weird. Sorting by
author wasn't super helpful either. People can search if they want a
specific author.
Added download counts to display. Needs the generator list to be updated
to provide the data though.

discovery page updates

---

app/assets/css/main.css
app/assets/js/script.js

https://github.com/yeoman/yeoman.io/issues/233
I referred online solutions for how I can fire a scroll event and get the point at which the nav bar starts to scroll below the header.
The value for the point at which a class is hard coded. Was hoping someone can suggest a better way to get the value?

issue#233 add sticky sidebar

---

app/assets/css/main.css

switch the context nav and content. content is now on the left and the subnav is on the right.
fixes #215

switch nav and content

---

app/authoring/file-system.md

Line 62:
Changed "every files get" to "every file gets"

Fix file-system.md typo

---

app/assets/js/generator.js

depends on https://github.com/yeoman/yeoman-generator-list/pull/25

move to the list generated

---

app/assets/css/main.css
app/assets/js/generator.js
app/generators/index.html

Adds download counts to the list and when it was last updated. Also uses the smaller format from https://github.com/yeoman/yeoman-generator-list/pull/28

list updates to add downloads and last updated

---

app/authoring/composability.md

Hope you fix that because it is misleading.

The peer-dependencies link is broken - see the new one

---

app/authoring/testing.md

Fixes link to test helpers API in the documentation.

Fixes link to test helpers API

---

app/learning/faq.md

Fix small English grammar mistake

Fix small English mistake

---

app/_posts/blog/2015-10-15-generator-gulp-angular-v1.md

List render is wrong. I fix problem with copy format of article `2014-05-12-generator-karma-rewrite.md`

Fix list and typo in article gga-v1

---

app/authoring/composability.md

Clarified status of end user initiated composition

---

app/authoring/index.md

anchored link

---

app/authoring/file-system.md

Update for possesive voice

---

Gruntfile.js
app/_includes/foot.html
app/assets/js/generator.js

still keeps the blacklist here for the moment as moving it to the generator-list repo requires redeploying on every update and thats not automated yet

remove blacklist from generators logic

---

app/_includes/head.html

Hi guys, :smile: 
I set the *Google Fonts link* to **a relative URL**.
*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

Using Protocol Relative URLs to Switch between HTTP and HTTPS

---

app/codelab/install-generators.md

Angular generator now needs generator-karma so its breaking the codelab. 
You can see their new requirements here: 
https://github.com/yeoman/generator-angular#readme

Update install-generators.md because Angular generator now needs generator-karma

---

app/contributing/index.md

Changed the core system description to include the 'environment' instead of the 'runner'
resolves #604

Updated app/contributing/index.md

---

app/authoring/composability.md

- add code example for managing composition execution

composability: improve composition execution description

---

app/authoring/composability.md

Looking for output of generator the input should be 'writing - turbo'

fix conlose.log input

---

app/learning/resources.md

ATM the [resources page](http://yeoman.io/learning/resources.html) is crashing, there was an invalid BOM char pushed into the .md file. This PR removes that.

resources.md: removes unnecessary BOM character

---

app/assets/css/main.css

Sub menu items line-height problem fixed.Solves problem in a small screen.

main-nav sub list-items problem fixed

---

app/assets/css/404.css
app/assets/css/codelab.css
app/assets/css/footer.css
app/assets/css/main.css
app/learning/faq.md

css format updated and character image has been resized in the faq page. but size is not suitable as a conceptual.

a few css fix

---

app/assets/css/main.css
app/assets/js/script.js

sidebar-fix

---

app/assets/js/script.js

fixed generator list

---

app/authoring/user-interactions.md

documentaion update

---

app/codelab/index.md

Update authors codelab

---

app/codelab/preview-inbrowser.md

close https://github.com/yeoman/yeoman/issues/1621

Add a note about livereloading and test

---

app/_posts/blog/2016-07-13-generator-m-ionic-js-fatigue-and-transitioning-to-typescript-angular-2-and-ionic-2.md

Hi @SBoudrias,
thanks for your message. I'm opening this PR as you proposed. 
1. The **images** are currently hosted through my own github, let me know if you want me to change that.
1. Apart form giving a **quick intro** into our generator and its purpose, I wrote this blog article mainly to pick up on **discussions regarding recent development-tool trends** that rather produce *framework-clis* than building flexible, open and extensible systems like [fountainjs](http://fountainjs.io/). I'm mostly referring to these discussions [here](https://github.com/angular/angular-cli/issues/49#issuecomment-206065079) (Angular CLI), [here](https://github.com/driftyco/ionic-cli/issues/845) (Ionic CLI) and [here](https://github.com/yeoman/yeoman/issues/1571) (Yeoman Themes 2016)
1. The **backlinks to …

Blog: generator-m-ionic post - first draft

---

app/codelab/local-storage.md

Add note on codelab step 7

---

app/codelab/scaffold-app.md

Probably you mean "webpack" not "wepack"

Changed words "wepack" to "webpack"

---

app/authoring/testing.md

current link was resulting in a 404

fix link to yeoman-test API docs

---

app/authoring/index.md

Small clarification on which file - index.js  - to add the generator commands to. Save some minute time understanding.

add clarification to which file to use in auth index section

---

app/codelab/preview-inbrowser.md

Don't forgot the test! -> Don't forget the test!

Fixed spelling

---

app/index.html

That’s it :octocat: 
yeoman/yeoman#1646

Add myself to the homepage

---

app/index.html

The most selfish PR :blush:
Related to https://github.com/yeoman/yeoman/issues/1649

Add my face :sweat_smile:

---

app/contributing/index.md

Add Gitter chat to community involvement

---

app/authoring/running-context.md

Fix typos in running-context.md

---

app/assets/css/main.css
app/generators/index.html

Closes #736 by adding a spinning circle loading indicator to the generators page.

Enhances visuals — add an animated loading indicator to the generators page

---

app/codelab/run-unit-tests.md

When trying to run Karma tests, i was getting : "PhantomJS failed 2 times (timeout). Giving up."
as this thread says, i corrected it by adding the entry 127.0.0.1 localhost to the etc/hosts file

Windows 7, Karma issue

---

app/authoring/debugging.md

change https://nodejs.org/en/docs/inspector/ plain string to [Node Debugging Guide](https://nodejs.org/en/docs/inspector/)

Updage debugging.md

---

app/assets/js/script.js

Update script.js
Fix incorrect sidebar positioning

Fix the incorrect positioning of the sidebar

---

app/authoring/file-system.md
app/authoring/user-interactions.md

I've updated example to show `prompting` and `writing` methods in the same class.

User answers from 'prompting' stage used at 'writing' stage.

---

app/authoring/testing.md

Added in https://github.com/yeoman/yeoman-test/pull/44

Testing a generator by importing it as a module

---

app/assets/js/generator.js

This will allow us to have more focused analytics on Yeoman alone (let me know if you don't have access to that yet)

add analytics tags to search

---

app/authoring/integrating-yeoman.md

I figured this out by searching TypeScript typings for Yeoman for *adapter*. Seems to work.

Document how to actually apply a custom adapter

---

app/authoring/debugging.md

Hi, npx solves path by itself.

Simplify the debugging page

---

app/learning/resources.md

Hello Yeoman team,
We, at Hsoub Academy, have recently translated the Getting Started and Let’s scaffold a Web App pages into Arabic, and we would like to add link to the translated tutorial in your resources page.
Thank you very mush.

resources.md: Add Arabic translation to the Translations section

---

app/learning/resources.md

I have written an article with the title "Generate Microservices Quickly with Yeoman." It is a simple how-to guide for backend engineers to build microservices quickly for their teams. I wish it could be included in the resource list to help developers implement Yeoman as a microservices generator.

Add an article to resources.md

---

app/_includes/foot.html

Deletes the `google-analytics.com` tracking script altogether.
Fixes #835.
I can't run the site locally right now per #833 🙃 so someone should definitely validate that I didn't miss anything. I searched for `ga`, `google.+analytics`, etc. and this was the only line that came up for GA besides docs in `app/misc/insight.md`.

feat: remove Google Analytics (GA) from the site

---

app/index.html

fix: correct npm scripts link formatting on homepage
